include ../config
all:
clean:
install:
	install -D -o root -g root -m 0644 order.bfa ${DOCDIR}/order.bfa
	install -D -o root -g root -m 0644 hello.bfa ${DOCDIR}/hello.bfa
uninstall:
	rm -r ${DOCDIR}/*.bfa
